### ISSUE TITLE
Why 15MB attachment limit?

### ISSUE THREAD

**Issue by mwitt1337** [jscarle/Freshdesk.NET#1]
Hello and thanks for starting this project. I'm a developer working on some code that already implemented the Freshdesk API v2 but I'm having issues creating a ticket with multiple attachments > 15MB in total. 

Is the 15MB total attachment size limit caused by the Freshdesk API? and if so do you know if there is documentation on that? I've tried to adjust web.config files to adjust response size limits but nothing seems to work.

**Comment by jscarle** [comment]
Wow, this flew completely under the radar. I know if it's been a long time... is this still relevant?

**Comment by jscarle** [comment]
No answer.
